### ISSUE TITLE
Exploration on which technologies are going to be used, and the solution for implementing required features.

### ISSUE THREAD

**Issue by oktay-sen** [Assis10t/assis10t#2]
Before starting any serious work, we need to make sure we experiment and have a consensus on the solution we're going to implement.

**Comment by oktay-sen** [comment]
Relates to #17

**Comment by oktay-sen** [comment]
We have done this on the Web end, how are the other teams doing?

**Comment by APRader** [comment]
Robot software is planning on using Raspberry Pi.

**Comment by oktay-sen** [comment]
Closing out of inactivity
