### ISSUE TITLE
Investigate university-provided options for hosting the server

### ISSUE THREAD

**Issue by oktay-sen** [Assis10t/assis10t#22]
Tardis?

**Comment by freddiejbawden** [comment]
Looks like TARDIS is a really good option, only downside is that it is linked to a uni account. I will look into allowing access from multiple users.

https://wiki.tardis.ed.ac.uk/wiki/Web_Service

**Comment by freddiejbawden** [comment]
https://wiki.tardis.ed.ac.uk/wiki/Tardis_Beginner_Tutorials

**Comment by freddiejbawden** [comment]
I've put in an application for a TARDIS account

**Comment by freddiejbawden** [comment]
Got a tardis account, will try and host a node server and a static page by then end of the week

**Comment by freddiejbawden** [comment]
Glitch could also be an option

**Comment by oktay-sen** [comment]
We can also use Firebase Functions, but the limitation is that it's not something that runs 24/7, but rather a few functions that run in response to Firebase updates. It's possible to design our system around this limitation, but I don't think it's worth the dev cost.

**Comment by freddiejbawden** [comment]
> We got clarification that even things like TARDIS & student.compute will count against our budget at the end, to simulate a startup feel. We need permanently free options. Glitch sounds good, but Heroku also has a free tier that we can run 24/7, and we can use Travis to auto-deploy the app whenever we push to master, for example.

Hmm, that's annoying. Heroku sounds better since you need to ping Glitch to wake it from what I understand. 

> We can also use Firebase Functions, but the limitation is that it's not something that runs 24/7, but rather a few functions that run in response to Firebase updates. It's possible to design our system around this limitation, but I don't think it's worth the dev cost.

Firebase Functions would keep everything more contained and prevent having to manage both the Firebase and the node server. Using a robot status field in the database would mean we can handle giving the robot instructions?

**Comment by oktay-sen** [comment]
> Heroku sounds better since you need to ping Glitch to wake it from what I understand.

Heroku has the same limitation in its free tier, but as far as I understand, it just means the first network request will have some latency as it wakes up, and it'll work fine as we keep using the server. We can make sure we keep the server awake during demos and we should be fine.

> Firebase Functions would keep everything more contained and prevent having to manage both the Firebase and the node server. Using a robot status field in the database would mean we can handle giving the robot instructions?

The ideal scenario in my head is that the server is always on and always listening to new socket connections. The robot just has to connect to a pre-defined IP address when it boots up, and the server will start sending instructions right away.

With Firebase Functions, we would have to implement something different. We could make Firebase Functions a REST API, and the robot can keep sending GET requests to receive commands, and do POST requests to update its status. AFAIK, there's a latency cost to doing a REST API vs a TCP socket, but it could be a viable solution as well.

Yet another solution is to use Firebase Database as a middleman for robot communication. Firebase functions put a list of commands to execute into the database, and the robot reads them in order. The robot also constantly updates its status information in the database, which can be read by the rest of the system. I think we should discuss these options in the next meeting.

**Comment by freddiejbawden** [comment]
> I think we should discuss these options in the next meeting.

Agreed, think we need a whiteboard

**Comment by oktay-sen** [comment]
We will start with Firebase Functions updating the database, and the robot reading from the database.

**Comment by oktay-sen** [comment]
Because robot wifi doesn't have an internet connection, and getting internet access to the robot would be costly/potentially not allowed, we will probably switch to a local solution where everything works through localhost. In that case, a node/express server with a mongodb/sql/graphql database would be the center of the operation.

**Comment by oktay-sen** [comment]
We're using a node/express server with mongodb database in the local network.
