### ISSUE TITLE
Create Firebase Project

### ISSUE THREAD

**Issue by oktay-sen** [Assis10t/assis10t#33]

**Comment by freddiejbawden** [comment]
I'll set up a G account for the system

**Comment by freddiejbawden** [comment]
Actually we can just share the project

**Comment by freddiejbawden** [comment]
@oktay-sen should we use NoSQL? or realtime database?

**Comment by freddiejbawden** [comment]
I think RealtimeDatabase's querying is more powerful but NoSQL would give us mega flexibility

**Comment by oktay-sen** [comment]
I already created one actually. We should use Firestore as it's almost objectively better than Realtime Database, and I think the coursework last semester recommended it.

**Comment by freddiejbawden** [comment]
@oktay-sen can we close this then?
